/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppAssignmentsRouteImport } from './routes/_app.assignments'
import { Route as AppContactRouteImport } from './routes/_app.contact'
import { Route as AppGrantImportRouteImport } from './routes/_app.grant-import'
import { Route as AppGrantRankingsRouteImport } from './routes/_app.grant-rankings'
import { Route as AppGrantRubricRouteImport } from './routes/_app.grant-rubric'
import { Route as AppHelpRouteImport } from './routes/_app.help'
import { Route as AppImportRouteImport } from './routes/_app.import'
import { Route as AppTopRouteImport } from './routes/_app.top'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AppApplicantsIndexRouteImport } from './routes/_app.applicants.index'
import { Route as AppApplicantsIdRouteImport } from './routes/_app.applicants.$id'
import { Route as AppGrantsIndexRouteImport } from './routes/_app.grants.index'
import { Route as AppGrantsIdRouteImport } from './routes/_app.grants.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssignmentsRoute = AppAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AppRoute,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppRoute,
} as any)
const AppGrantImportRoute = AppGrantImportRouteImport.update({
  id: '/grant-import',
  path: '/grant-import',
  getParentRoute: () => AppRoute,
} as any)
const AppGrantRankingsRoute = AppGrantRankingsRouteImport.update({
  id: '/grant-rankings',
  path: '/grant-rankings',
  getParentRoute: () => AppRoute,
} as any)
const AppGrantRubricRoute = AppGrantRubricRouteImport.update({
  id: '/grant-rubric',
  path: '/grant-rubric',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppTopRoute = AppTopRouteImport.update({
  id: '/top',
  path: '/top',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppApplicantsIndexRoute = AppApplicantsIndexRouteImport.update({
  id: '/applicants/',
  path: '/applicants/',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicantsIdRoute = AppApplicantsIdRouteImport.update({
  id: '/applicants/$id',
  path: '/applicants/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppGrantsIndexRoute = AppGrantsIndexRouteImport.update({
  id: '/grants/',
  path: '/grants/',
  getParentRoute: () => AppRoute,
} as any)
const AppGrantsIdRoute = AppGrantsIdRouteImport.update({
  id: '/grants/$id',
  path: '/grants/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/assignments': typeof AppAssignmentsRoute
  '/contact': typeof AppContactRoute
  '/grant-import': typeof AppGrantImportRoute
  '/grant-rankings': typeof AppGrantRankingsRoute
  '/grant-rubric': typeof AppGrantRubricRoute
  '/help': typeof AppHelpRoute
  '/import': typeof AppImportRoute
  '/top': typeof AppTopRoute
  '/users': typeof AppUsersRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/applicants/$id': typeof AppApplicantsIdRoute
  '/grants/$id': typeof AppGrantsIdRoute
  '/applicants/': typeof AppApplicantsIndexRoute
  '/grants/': typeof AppGrantsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/assignments': typeof AppAssignmentsRoute
  '/contact': typeof AppContactRoute
  '/grant-import': typeof AppGrantImportRoute
  '/grant-rankings': typeof AppGrantRankingsRoute
  '/grant-rubric': typeof AppGrantRubricRoute
  '/help': typeof AppHelpRoute
  '/import': typeof AppImportRoute
  '/top': typeof AppTopRoute
  '/users': typeof AppUsersRoute
  '/': typeof AppIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/applicants/$id': typeof AppApplicantsIdRoute
  '/grants/$id': typeof AppGrantsIdRoute
  '/applicants': typeof AppApplicantsIndexRoute
  '/grants': typeof AppGrantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_app/assignments': typeof AppAssignmentsRoute
  '/_app/contact': typeof AppContactRoute
  '/_app/grant-import': typeof AppGrantImportRoute
  '/_app/grant-rankings': typeof AppGrantRankingsRoute
  '/_app/grant-rubric': typeof AppGrantRubricRoute
  '/_app/help': typeof AppHelpRoute
  '/_app/import': typeof AppImportRoute
  '/_app/top': typeof AppTopRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/': typeof AppIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_app/applicants/$id': typeof AppApplicantsIdRoute
  '/_app/grants/$id': typeof AppGrantsIdRoute
  '/_app/applicants/': typeof AppApplicantsIndexRoute
  '/_app/grants/': typeof AppGrantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/assignments'
    | '/contact'
    | '/grant-import'
    | '/grant-rankings'
    | '/grant-rubric'
    | '/help'
    | '/import'
    | '/top'
    | '/users'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/applicants/$id'
    | '/grants/$id'
    | '/applicants/'
    | '/grants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/assignments'
    | '/contact'
    | '/grant-import'
    | '/grant-rankings'
    | '/grant-rubric'
    | '/help'
    | '/import'
    | '/top'
    | '/users'
    | '/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/applicants/$id'
    | '/grants/$id'
    | '/applicants'
    | '/grants'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_app/assignments'
    | '/_app/contact'
    | '/_app/grant-import'
    | '/_app/grant-rankings'
    | '/_app/grant-rubric'
    | '/_app/help'
    | '/_app/import'
    | '/_app/top'
    | '/_app/users'
    | '/_app/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_app/applicants/$id'
    | '/_app/grants/$id'
    | '/_app/applicants/'
    | '/_app/grants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assignments': {
      id: '/_app/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AppAssignmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contact': {
      id: '/_app/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grant-import': {
      id: '/_app/grant-import'
      path: '/grant-import'
      fullPath: '/grant-import'
      preLoaderRoute: typeof AppGrantImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grant-rankings': {
      id: '/_app/grant-rankings'
      path: '/grant-rankings'
      fullPath: '/grant-rankings'
      preLoaderRoute: typeof AppGrantRankingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grant-rubric': {
      id: '/_app/grant-rubric'
      path: '/grant-rubric'
      fullPath: '/grant-rubric'
      preLoaderRoute: typeof AppGrantRubricRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import': {
      id: '/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/top': {
      id: '/_app/top'
      path: '/top'
      fullPath: '/top'
      preLoaderRoute: typeof AppTopRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/applicants/': {
      id: '/_app/applicants/'
      path: '/applicants'
      fullPath: '/applicants/'
      preLoaderRoute: typeof AppApplicantsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/applicants/$id': {
      id: '/_app/applicants/$id'
      path: '/applicants/$id'
      fullPath: '/applicants/$id'
      preLoaderRoute: typeof AppApplicantsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grants/': {
      id: '/_app/grants/'
      path: '/grants'
      fullPath: '/grants/'
      preLoaderRoute: typeof AppGrantsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grants/$id': {
      id: '/_app/grants/$id'
      path: '/grants/$id'
      fullPath: '/grants/$id'
      preLoaderRoute: typeof AppGrantsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAssignmentsRoute: typeof AppAssignmentsRoute
  AppContactRoute: typeof AppContactRoute
  AppGrantImportRoute: typeof AppGrantImportRoute
  AppGrantRankingsRoute: typeof AppGrantRankingsRoute
  AppGrantRubricRoute: typeof AppGrantRubricRoute
  AppHelpRoute: typeof AppHelpRoute
  AppImportRoute: typeof AppImportRoute
  AppTopRoute: typeof AppTopRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppApplicantsIdRoute: typeof AppApplicantsIdRoute
  AppGrantsIdRoute: typeof AppGrantsIdRoute
  AppApplicantsIndexRoute: typeof AppApplicantsIndexRoute
  AppGrantsIndexRoute: typeof AppGrantsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssignmentsRoute: AppAssignmentsRoute,
  AppContactRoute: AppContactRoute,
  AppGrantImportRoute: AppGrantImportRoute,
  AppGrantRankingsRoute: AppGrantRankingsRoute,
  AppGrantRubricRoute: AppGrantRubricRoute,
  AppHelpRoute: AppHelpRoute,
  AppImportRoute: AppImportRoute,
  AppTopRoute: AppTopRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
  AppApplicantsIdRoute: AppApplicantsIdRoute,
  AppGrantsIdRoute: AppGrantsIdRoute,
  AppApplicantsIndexRoute: AppApplicantsIndexRoute,
  AppGrantsIndexRoute: AppGrantsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
