/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppTopRouteImport } from './routes/_app.top'
import { Route as AppImportRouteImport } from './routes/_app.import'
import { Route as AppHelpRouteImport } from './routes/_app.help'
import { Route as AppContactRouteImport } from './routes/_app.contact'
import { Route as AppApplicantsIndexRouteImport } from './routes/_app.applicants.index'
import { Route as AppApplicantsIdRouteImport } from './routes/_app.applicants.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTopRoute = AppTopRouteImport.update({
  id: '/top',
  path: '/top',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicantsIndexRoute = AppApplicantsIndexRouteImport.update({
  id: '/applicants/',
  path: '/applicants/',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicantsIdRoute = AppApplicantsIdRouteImport.update({
  id: '/applicants/$id',
  path: '/applicants/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/contact': typeof AppContactRoute
  '/help': typeof AppHelpRoute
  '/import': typeof AppImportRoute
  '/top': typeof AppTopRoute
  '/users': typeof AppUsersRoute
  '/applicants/$id': typeof AppApplicantsIdRoute
  '/applicants/': typeof AppApplicantsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/contact': typeof AppContactRoute
  '/help': typeof AppHelpRoute
  '/import': typeof AppImportRoute
  '/top': typeof AppTopRoute
  '/users': typeof AppUsersRoute
  '/': typeof AppIndexRoute
  '/applicants/$id': typeof AppApplicantsIdRoute
  '/applicants': typeof AppApplicantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/contact': typeof AppContactRoute
  '/_app/help': typeof AppHelpRoute
  '/_app/import': typeof AppImportRoute
  '/_app/top': typeof AppTopRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/': typeof AppIndexRoute
  '/_app/applicants/$id': typeof AppApplicantsIdRoute
  '/_app/applicants/': typeof AppApplicantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/contact'
    | '/help'
    | '/import'
    | '/top'
    | '/users'
    | '/applicants/$id'
    | '/applicants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/contact'
    | '/help'
    | '/import'
    | '/top'
    | '/users'
    | '/'
    | '/applicants/$id'
    | '/applicants'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/contact'
    | '/_app/help'
    | '/_app/import'
    | '/_app/top'
    | '/_app/users'
    | '/_app/'
    | '/_app/applicants/$id'
    | '/_app/applicants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/top': {
      id: '/_app/top'
      path: '/top'
      fullPath: '/top'
      preLoaderRoute: typeof AppTopRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import': {
      id: '/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contact': {
      id: '/_app/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/applicants/': {
      id: '/_app/applicants/'
      path: '/applicants'
      fullPath: '/applicants/'
      preLoaderRoute: typeof AppApplicantsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/applicants/$id': {
      id: '/_app/applicants/$id'
      path: '/applicants/$id'
      fullPath: '/applicants/$id'
      preLoaderRoute: typeof AppApplicantsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppContactRoute: typeof AppContactRoute
  AppHelpRoute: typeof AppHelpRoute
  AppImportRoute: typeof AppImportRoute
  AppTopRoute: typeof AppTopRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppApplicantsIdRoute: typeof AppApplicantsIdRoute
  AppApplicantsIndexRoute: typeof AppApplicantsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppContactRoute: AppContactRoute,
  AppHelpRoute: AppHelpRoute,
  AppImportRoute: AppImportRoute,
  AppTopRoute: AppTopRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
  AppApplicantsIdRoute: AppApplicantsIdRoute,
  AppApplicantsIndexRoute: AppApplicantsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
